Repair/Reinstall Instructions for Sequoia
The `nix run .#build-switch` command failed with the following error on Sequoia as Nix was installed after upgrading from Sonoma.

```
error: Build user group has mismatching GID, aborting activation
The default Nix build user group ID was changed from 30000 to 350.
You are currently managing Nix build users with nix-darwin, but your
nixbld group has GID 350, whereas we expected 30000.

Possible causes include setting up a new Nix installation with an
existing nix-darwin configuration, setting up a new nix-darwin
installation with an existing Nix installation, or manually increasing
your `system.stateVersion` setting.

You can set the configured group ID to match the actual value:

    ids.gids.nixbld = 350;

We do not recommend trying to change the group ID with macOS user
management tools without a complete uninstallation and reinstallation
```

The root cause is mentioned in https://determinate.systems/posts/nix-support-for-macos-sequoia/, which had to be done prior to  the upgrade. Since the upgrade was already done, the fix is to reinstall Nix with expected GID for `nixbld`.