Fix: Build errors on Sequoia (#143)
* Fix: The option definition `nix.gc.user' and `services.nix-daemon.enable' no longer has any effect

When running `nix run .#build` on macOS Sequoia, the following error was occurred:

```
error:
       … while evaluating the attribute 'value'
         at /nix/store/zbvf6xwri9kvf42xl3vai3mx8jry6ax8-source/lib/modules.nix:853:9:
          852|     in warnDeprecation opt //
          853|       { value = addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          854|         inherit (res.defsFinal') highestPrio;

       … while evaluating the option `system.build':

       … while evaluating the attribute 'mergedValue'
         at /nix/store/zbvf6xwri9kvf42xl3vai3mx8jry6ax8-source/lib/modules.nix:888:5:
          887|     # Type-check the remaining definitions, and merge them. Or throw if no definitions.
          888|     mergedValue =
             |     ^
          889|       if isDefined then

       … while evaluating definitions from `/nix/store/qp24528rxcnjskxsqs40aybaiqp7qq51-source/modules/system':

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error:
       Failed assertions:
       - The option definition `nix.gc.user' in `/nix/store/zkkcgy73xlq8p4vk46jrxs0rm02aq8zx-source/hosts/darwin' no longer has any effect; please remove it.
       The garbage collection service now always runs as `root`.

       - The option definition `services.nix-daemon.enable' in `/nix/store/zkkcgy73xlq8p4vk46jrxs0rm02aq8zx-source/hosts/darwin' no longer has any effect; please remove it.
       nix-darwin now manages nix-daemon unconditionally when
       `nix.enable` is on.
```

After making the amendments as advised, the issue was resolved.

* Repair/Reinstall Instructions for Sequoia

The `nix run .#build-switch` command failed with the following error on Sequoia as Nix was installed after upgrading from Sonoma.

```
error: Build user group has mismatching GID, aborting activation
The default Nix build user group ID was changed from 30000 to 350.
You are currently managing Nix build users with nix-darwin, but your
nixbld group has GID 350, whereas we expected 30000.

Possible causes include setting up a new Nix installation with an
existing nix-darwin configuration, setting up a new nix-darwin
installation with an existing Nix installation, or manually increasing
your `system.stateVersion` setting.

You can set the configured group ID to match the actual value:

    ids.gids.nixbld = 350;

We do not recommend trying to change the group ID with macOS user
management tools without a complete uninstallation and reinstallation
```

The root cause is mentioned in https://determinate.systems/posts/nix-support-for-macos-sequoia/, which had to be done prior to  the upgrade. Since the upgrade was already done, the fix is to reinstall Nix with expected GID for `nixbld`.

* Fix: Spelling and grammar

A few typos have ben fixed.